set(TOOLCHAIN_TRIPLE aarch64-buildroot-linux-gnu)
set(TOOLCHAIN_BASE_DIR /opt/systemcore-aarch64-toolchain)
set(TOOLCHAIN_ROOTFS_DIR ${TOOLCHAIN_BASE_DIR}/${TOOLCHAIN_TRIPLE}/sysroot)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_SYSROOT "${TOOLCHAIN_ROOTFS_DIR}")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-psabi")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-psabi")

set(CMAKE_C_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-g++)

set(CMAKE_AR ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-ar)
set(CMAKE_AS ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-as)
set(CMAKE_NM ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-nm)
set(CMAKE_LINKER ${TOOLCHAIN_BASE_DIR}/bin/${TOOLCHAIN_TRIPLE}-ld)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

list(APPEND CMAKE_PREFIX_PATH "${TOOLCHAIN_ROOTFS_DIR}")
