// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MOTIONCORE_PROTO_MOTIONCORE_NPB_H_INCLUDED
#define PB_MOTIONCORE_PROTO_MOTIONCORE_NPB_H_INCLUDED
#include <pb.h>
#include <span>
#include <string_view>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _motioncore_proto_ProtobufMotioncoreEncoder {
    static const pb_msgdesc_t* msg_descriptor(void) noexcept;
    static std::string_view msg_name(void) noexcept;
    static pb_filedesc_t file_descriptor(void) noexcept;

    int32_t Position;
    int32_t Velocity;
} motioncore_proto_ProtobufMotioncoreEncoder;

typedef struct _motioncore_proto_ProtobufRawMotioncoreData {
    static const pb_msgdesc_t* msg_descriptor(void) noexcept;
    static std::string_view msg_name(void) noexcept;
    static pb_filedesc_t file_descriptor(void) noexcept;

    pb_callback_t Encoder0;
    pb_callback_t Encoder1;
    pb_callback_t Encoder2;
    uint64_t Timestamp;
    uint32_t PinStates;
} motioncore_proto_ProtobufRawMotioncoreData;


/* Initializer values for message structs */
#define motioncore_proto_ProtobufMotioncoreEncoder_init_default {0, 0}
#define motioncore_proto_ProtobufRawMotioncoreData_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define motioncore_proto_ProtobufMotioncoreEncoder_init_zero {0, 0}
#define motioncore_proto_ProtobufRawMotioncoreData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define motioncore_proto_ProtobufMotioncoreEncoder_Position_tag 1
#define motioncore_proto_ProtobufMotioncoreEncoder_Velocity_tag 2
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder0_tag 1
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder1_tag 2
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder2_tag 3
#define motioncore_proto_ProtobufRawMotioncoreData_Timestamp_tag 4
#define motioncore_proto_ProtobufRawMotioncoreData_PinStates_tag 5

/* Struct field encoding specification for nanopb */
#define motioncore_proto_ProtobufMotioncoreEncoder_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    Position,          1) \
X(a, STATIC,   SINGULAR, INT32,    Velocity,          2)
#define motioncore_proto_ProtobufMotioncoreEncoder_CALLBACK NULL
#define motioncore_proto_ProtobufMotioncoreEncoder_DEFAULT NULL

#define motioncore_proto_ProtobufRawMotioncoreData_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  Encoder0,          1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  Encoder1,          2) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  Encoder2,          3) \
X(a, STATIC,   SINGULAR, UINT64,   Timestamp,         4) \
X(a, STATIC,   SINGULAR, UINT32,   PinStates,         5)
#define motioncore_proto_ProtobufRawMotioncoreData_CALLBACK pb_default_field_callback
#define motioncore_proto_ProtobufRawMotioncoreData_DEFAULT NULL
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder0_MSGTYPE motioncore_proto_ProtobufMotioncoreEncoder
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder1_MSGTYPE motioncore_proto_ProtobufMotioncoreEncoder
#define motioncore_proto_ProtobufRawMotioncoreData_Encoder2_MSGTYPE motioncore_proto_ProtobufMotioncoreEncoder

/* Maximum encoded size of messages (where known) */
/* motioncore_proto_ProtobufRawMotioncoreData_size depends on runtime parameters */
#define MOTIONCORE_PROTO_MOTIONCORE_NPB_H_MAX_SIZE motioncore_proto_ProtobufMotioncoreEncoder_size
#define motioncore_proto_ProtobufMotioncoreEncoder_size 22


#endif
