set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CROSS_PREFIX "aarch64-linux-gnu")

# Find the cross-compiler via brew prefix or fall back to PATH
execute_process(
    COMMAND brew --prefix aarch64-unknown-linux-gnu
    OUTPUT_VARIABLE TOOLCHAIN_ROOT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE BREW_RESULT
)

if(BREW_RESULT EQUAL 0)
    set(CMAKE_C_COMPILER   "${TOOLCHAIN_ROOT}/bin/${CROSS_PREFIX}-gcc")
    set(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT}/bin/${CROSS_PREFIX}-g++")
else()
    set(CMAKE_C_COMPILER   "${CROSS_PREFIX}-gcc")
    set(CMAKE_CXX_COMPILER "${CROSS_PREFIX}-g++")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
